/* Initial FS and Partnership views; keep the owner's gate evidence and authority rules. */
(() => {
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  S.initialFS=S.initialFS||{};S.partnerships=S.partnerships||[];
  $('panel-team')?.remove();$('modal-member')?.remove();$('modal-zh-report')?.remove();
  const project=()=>S.projects.find(p=>p.id===S.activeProjectId);
  const fmt=n=>Number(n).toLocaleString('en-GB',{maximumFractionDigits:2});
  renderFinance=function(){
    const p=project(),root=$('panel-finance');if(!p){root.innerHTML='<div class="empty-state">Select a project to prepare its Initial FS.</div>';return;}
    const f=S.initialFS[p.id]||{};
    const text=(key,label,placeholder)=>`<div class="field"><label class="lbl" for="fs-${key}">${label}</label><textarea id="fs-${key}" name="${key}" rows="3" placeholder="${esc(placeholder)}">${esc(f[key])}</textarea></div>`;
    const number=(key,label)=>`<div class="field"><label class="lbl" for="fs-${key}">${label}</label><input type="number" min="0" step="any" id="fs-${key}" name="${key}" value="${esc(f[key])}" placeholder="Not entered"></div>`;
    root.innerHTML=`<div class="hero"><div><div class="eyebrow">${esc(p.name)} / FEASIBILITY</div><h1>Initial FS</h1><p class="muted">Assess initial feasibility and assumptions before Gate G02.</p></div></div><form id="initial-fs-form"><div class="flow"><section class="card"><h2>Market & solution</h2>${text('market','Demand & market evidence','Customers, demand size, competitors, and validation sources.')}${text('technical','Technical feasibility & resources','Technology, site, capacity, and required resources.')}${text('assumptions','Critical assumptions','Assumptions for price, demand, capacity utilization, and delivery.')}</section><section class="card"><h2>Initial economics</h2><p class="muted mini">Unit: VND million. Revenue and OPEX are annual.</p>${number('capex','Initial CAPEX')}${number('revenue','Annual revenue')}${number('opex','Annual OPEX')}<div class="notice" id="fs-results"></div>${text('cashflow','Cash flow & scenarios','Investment schedule, working capital, tax, funding, and low / base / high scenarios.')}</section><section class="card"><h2>Risks & recommendation</h2>${text('risks','Risks & mitigations','Key risks, impacts, owners, and mitigations.')}${text('evidence','Documents & evidence','Links to the FS, quotations, surveys, and supporting documents.')}${text('recommendation','Recommendation / owner decision required','Conditions required for the owner to consider GO / Revise / No-Go.')}</section></div><div class="toolbar"><button class="btn btn-primary" type="submit">Save Initial FS</button><button class="btn" type="button" id="fs-gate">BIM / Gate owner</button></div></form><div class="notice">Initial FS is a preliminary assessment. These calculations exclude tax, working capital, financing, and the time value of money. Evidence and Gate decisions remain subject to owner governance and are never approved automatically.</div>`;
    const calc=()=>{const cap=$('fs-capex').value,rev=$('fs-revenue').value,op=$('fs-opex').value;const result=$('fs-results');if([cap,rev,op].some(v=>v==='')){result.textContent='Enter CAPEX, revenue, and OPEX to calculate initial metrics.';return;}const surplus=Number(rev)-Number(op);result.innerHTML=`<strong>Revenue − OPEX surplus:</strong> ${fmt(surplus)} VND m/year<br><strong>Simple payback:</strong> ${surplus>0&&Number(cap)>0?fmt(Number(cap)/surplus)+' years':surplus<=0?'Not available: the surplus is not positive.':'Not available: CAPEX is zero.'}`;};
    ['capex','revenue','opex'].forEach(k=>$('fs-'+k).oninput=calc);calc();
    $('initial-fs-form').onsubmit=e=>{e.preventDefault();S.initialFS[p.id]={...Object.fromEntries(new FormData(e.target)),updatedAt:ts()};saveLocal();toast('Initial FS saved · '+p.name);};
    $('fs-gate').onclick=()=>sw('bim',document.querySelector('.tab[onclick*="bim"]'));
  };
  const stages=['Sourcing','Engagement','Fit assessment','Agreement','Active partnership','On hold'];
  renderMa=function(){
    const p=project(),root=$('panel-ma');if(!p){root.innerHTML='<div class="empty-state">Select a project to manage Partnerships.</div>';return;}
    const rows=S.partnerships.filter(a=>a.projectId===p.id);
    root.innerHTML=`<div class="hero"><div><div class="eyebrow">${esc(p.name)} / PARTNERSHIP</div><h1>Partnership</h1><p class="muted">Partners supporting the concept, business model, and operating capability.</p></div><button class="btn btn-primary" id="partnership-add">+ Add partner</button></div><div class="owner-strip">${stages.map(s=>`<span class="tag">${esc(s)} · ${rows.filter(a=>a.stage===s).length}</span>`).join('')}</div><div class="card table-scroll"><table class="table-new"><thead><tr><th>Partner</th><th>Model / stage</th><th>Contribution & value</th><th>Next step</th><th></th></tr></thead><tbody>${rows.map(a=>`<tr><td><strong>${esc(a.name)}</strong><div class="muted mini">${esc(a.contact)}</div></td><td>${esc(a.model)}<div class="tag">${esc(a.stage)}</div></td><td>${esc(a.contribution)}<div class="muted">${esc(a.value)}</div></td><td>${esc(a.next)}<div class="muted mini">${esc(a.owner)} · ${esc(a.due)}</div></td><td><button class="btn" data-partnership-edit="${esc(a.id)}">Edit</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty-state">No partners yet. Add a partner with its contribution, expected value, and next step.</td></tr>'}</tbody></table></div><div class="notice">Delivery roles and RACI are managed in Team & Partners. Commitments requiring approval remain in Decisions under L1–L3 authority.</div>`;
    $('partnership-add').onclick=()=>editPartnership(p.id);root.querySelectorAll('[data-partnership-edit]').forEach(el=>el.onclick=()=>editPartnership(p.id,S.partnerships.find(a=>a.id===el.dataset.partnershipEdit)));
  };
  function editPartnership(projectId,a={}){
    $('partnership-dialog')?.remove();const d=document.createElement('dialog');d.id='partnership-dialog';d.className='portfolio-dialog';
    const input=(k,label,type='text')=>`<div class="field"><label class="lbl" for="pt-${k}">${label}</label><input id="pt-${k}" name="${k}" type="${type}" value="${esc(a[k])}" ${k==='name'?'required':''}></div>`;
    d.innerHTML=`<form><h2>${a.id?'Edit':'Add'} Partnership</h2>${input('name','Partner name *')}${input('contact','Primary contact')}${input('model','Partnership model')}<div class="field"><label class="lbl" for="pt-stage">Stage</label><select id="pt-stage" name="stage">${stages.map(s=>`<option ${a.stage===s?'selected':''}>${esc(s)}</option>`).join('')}</select></div>${input('contribution','Partner resources / contribution')}${input('value','Expected value / mutual benefit')}${input('next','Next step')}${input('owner','Owner')}${input('due','Due date','date')}<footer><button type="button" class="btn" id="pt-cancel">Cancel</button><button class="btn btn-primary" type="submit">Save Partnership</button></footer></form>`;document.body.appendChild(d);$('pt-cancel').onclick=()=>d.close();d.onclose=()=>d.remove();d.querySelector('form').onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.target));values.name=values.name.trim();if(!values.name)return;const item={...values,id:a.id||'PT-'+crypto.randomUUID(),projectId,updatedAt:ts()};const index=S.partnerships.findIndex(x=>x.id===item.id);if(index>=0)S.partnerships[index]=item;else S.partnerships.push(item);saveLocal();d.close();renderMa();toast('Partnership saved');};d.showModal();$('pt-name').focus();
  }
  const previousRender=renderAll;renderAll=function(){previousRender();if(S.activeTab==='ma')renderMa();};
  saveLocal();
})();



