/* Initial FS and Partnership views; keep the owner's gate evidence and authority rules. */
(() => {
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  S.initialFS=S.initialFS||{};S.partnerships=S.partnerships||[];
  $('panel-team')?.remove();$('modal-member')?.remove();$('modal-zh-report')?.remove();
  const project=()=>S.projects.find(p=>p.id===S.activeProjectId);
  const fmt=n=>Number(n).toLocaleString('vi-VN',{maximumFractionDigits:2});
  renderFinance=function(){
    const p=project(),root=$('panel-finance');if(!p){root.innerHTML='<div class="empty-state">Chọn dự án để lập Initial FS.</div>';return;}
    const f=S.initialFS[p.id]||{};
    const text=(key,label,placeholder)=>`<div class="field"><label class="lbl" for="fs-${key}">${label}</label><textarea id="fs-${key}" name="${key}" rows="3" placeholder="${esc(placeholder)}">${esc(f[key])}</textarea></div>`;
    const number=(key,label)=>`<div class="field"><label class="lbl" for="fs-${key}">${label}</label><input type="number" min="0" step="any" id="fs-${key}" name="${key}" value="${esc(f[key])}" placeholder="Chưa nhập"></div>`;
    root.innerHTML=`<div class="hero"><div><div class="eyebrow">${esc(p.name)} / FEASIBILITY</div><h1>Initial FS</h1><p class="muted">Đánh giá khả thi sơ bộ và giả định cần kiểm chứng trước Gate G02.</p></div></div><form id="initial-fs-form"><div class="flow"><section class="card"><h2>Thị trường & giải pháp</h2>${text('market','Nhu cầu & bằng chứng thị trường','Khách hàng, quy mô nhu cầu, đối thủ và nguồn kiểm chứng.')}${text('technical','Khả thi kỹ thuật & nguồn lực','Công nghệ, mặt bằng, công suất và nguồn lực cần thiết.')}${text('assumptions','Giả định quan trọng','Giả định về giá, nhu cầu, sử dụng công suất và triển khai.')}</section><section class="card"><h2>Kinh tế sơ bộ</h2><p class="muted mini">Đơn vị: triệu đồng. Doanh thu và OPEX theo năm.</p>${number('capex','CAPEX đầu tư ban đầu')}${number('revenue','Doanh thu / năm')}${number('opex','OPEX / năm')}<div class="notice" id="fs-results"></div>${text('cashflow','Dòng tiền & kịch bản','Lịch đầu tư, vốn lưu động, thuế, tài trợ và kịch bản thấp / cơ sở / cao.')}</section><section class="card"><h2>Rủi ro & đề xuất</h2>${text('risks','Rủi ro & phương án xử lý','Rủi ro chính, tác động, người phụ trách, cách giảm thiểu.')}${text('evidence','Tài liệu & bằng chứng','Link FS, báo giá, khảo sát và các tài liệu liên quan.')}${text('recommendation','Đề xuất / quyết định cần owner','Điều kiện cần bổ sung để owner xem xét GO / Revise / No-Go.')}</section></div><div class="toolbar"><button class="btn btn-primary" type="submit">Lưu Initial FS</button><button class="btn" type="button" id="fs-gate">BIM / Gate owner</button></div></form><div class="notice">Initial FS là đánh giá sơ bộ. Kết quả tính dưới đây chưa gồm thuế, vốn lưu động, tài trợ và giá trị thời gian của tiền. Evidence và quyết định qua gate vẫn theo framework owner, không tự động phê duyệt.</div>`;
    const calc=()=>{const cap=$('fs-capex').value,rev=$('fs-revenue').value,op=$('fs-opex').value;const result=$('fs-results');if([cap,rev,op].some(v=>v==='')){result.textContent='Nhập CAPEX, doanh thu và OPEX để xem chỉ số sơ bộ.';return;}const surplus=Number(rev)-Number(op);result.innerHTML=`<strong>Chênh lệch doanh thu − OPEX:</strong> ${fmt(surplus)} tr.đ/năm<br><strong>Hoàn vốn đơn giản:</strong> ${surplus>0&&Number(cap)>0?fmt(Number(cap)/surplus)+' năm':surplus<=0?'Không xác định: chênh lệch không dương.':'Chưa xác định: CAPEX bằng 0.'}`;};
    ['capex','revenue','opex'].forEach(k=>$('fs-'+k).oninput=calc);calc();
    $('initial-fs-form').onsubmit=e=>{e.preventDefault();S.initialFS[p.id]={...Object.fromEntries(new FormData(e.target)),updatedAt:ts()};saveLocal();toast('Đã lưu Initial FS · '+p.name);};
    $('fs-gate').onclick=()=>sw('bim',document.querySelector('.tab[onclick*="bim"]'));
  };
  const stages=['Tìm kiếm','Trao đổi','Đánh giá phù hợp','Thỏa thuận','Đang hợp tác','Tạm dừng'];
  renderMa=function(){
    const p=project(),root=$('panel-ma');if(!p){root.innerHTML='<div class="empty-state">Chọn dự án để quản lý Partnership.</div>';return;}
    const rows=S.partnerships.filter(a=>a.projectId===p.id);
    root.innerHTML=`<div class="hero"><div><div class="eyebrow">${esc(p.name)} / PARTNERSHIP</div><h1>Partnership</h1><p class="muted">Đối tác cùng xây concept, mô hình kinh doanh và năng lực vận hành.</p></div><button class="btn btn-primary" id="partnership-add">+ Thêm đối tác</button></div><div class="owner-strip">${stages.map(s=>`<span class="tag">${esc(s)} · ${rows.filter(a=>a.stage===s).length}</span>`).join('')}</div><div class="card table-scroll"><table class="table-new"><thead><tr><th>Đối tác</th><th>Hình thức / giai đoạn</th><th>Đóng góp & giá trị</th><th>Bước tiếp theo</th><th></th></tr></thead><tbody>${rows.map(a=>`<tr><td><strong>${esc(a.name)}</strong><div class="muted mini">${esc(a.contact)}</div></td><td>${esc(a.model)}<div class="tag">${esc(a.stage)}</div></td><td>${esc(a.contribution)}<div class="muted">${esc(a.value)}</div></td><td>${esc(a.next)}<div class="muted mini">${esc(a.owner)} · ${esc(a.due)}</div></td><td><button class="btn" data-partnership-edit="${esc(a.id)}">Sửa</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty-state">Chưa có đối tác. Thêm đối tác và ghi rõ đóng góp, giá trị kỳ vọng và bước tiếp theo.</td></tr>'}</tbody></table></div><div class="notice">Thành viên thực thi và RACI quản lý tại Đội ngũ & Đối tác. Các cam kết cần phê duyệt vẫn ghi tại Decisions theo thẩm quyền L1–L3.</div>`;
    $('partnership-add').onclick=()=>editPartnership(p.id);root.querySelectorAll('[data-partnership-edit]').forEach(el=>el.onclick=()=>editPartnership(p.id,S.partnerships.find(a=>a.id===el.dataset.partnershipEdit)));
  };
  function editPartnership(projectId,a={}){
    $('partnership-dialog')?.remove();const d=document.createElement('dialog');d.id='partnership-dialog';d.className='portfolio-dialog';
    const input=(k,label,type='text')=>`<div class="field"><label class="lbl" for="pt-${k}">${label}</label><input id="pt-${k}" name="${k}" type="${type}" value="${esc(a[k])}" ${k==='name'?'required':''}></div>`;
    d.innerHTML=`<form><h2>${a.id?'Sửa':'Thêm'} Partnership</h2>${input('name','Tên đối tác *')}${input('contact','Đầu mối / liên hệ')}${input('model','Hình thức hợp tác')}<div class="field"><label class="lbl" for="pt-stage">Giai đoạn</label><select id="pt-stage" name="stage">${stages.map(s=>`<option ${a.stage===s?'selected':''}>${esc(s)}</option>`).join('')}</select></div>${input('contribution','Nguồn lực / đóng góp của đối tác')}${input('value','Giá trị kỳ vọng / lợi ích hai bên')}${input('next','Bước tiếp theo')}${input('owner','Người phụ trách')}${input('due','Hạn hoàn thành','date')}<footer><button type="button" class="btn" id="pt-cancel">Hủy</button><button class="btn btn-primary" type="submit">Lưu Partnership</button></footer></form>`;document.body.appendChild(d);$('pt-cancel').onclick=()=>d.close();d.onclose=()=>d.remove();d.querySelector('form').onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.target));values.name=values.name.trim();if(!values.name)return;const item={...values,id:a.id||'PT-'+crypto.randomUUID(),projectId,updatedAt:ts()};const index=S.partnerships.findIndex(x=>x.id===item.id);if(index>=0)S.partnerships[index]=item;else S.partnerships.push(item);saveLocal();d.close();renderMa();toast('Đã lưu Partnership');};d.showModal();$('pt-name').focus();
  }
  const previousRender=renderAll;renderAll=function(){previousRender();if(S.activeTab==='ma')renderMa();};
  saveLocal();
})();

